### ISSUE TITLE
AVX instructions loading beyond end of image buffer

### ISSUE THREAD

**Issue by nedm2** [komrad36/KFAST#3]
Hi, firstly thank you very much for your excellent work on KFAST!

I have a question about the 32 byte loads performed in processCols. I noticed that when I run valgrind on KFAST I get some complaints like this:

==21867== Invalid read of size 32
==21867==    at 0x5A2D57: _mm256_cmpgt_epi8 (avx2intrin.h:261)
==21867==    by 0x5A2D57: processCols<false, false> (KFastAVX2.h:207)
==21867==    by 0x5A2D57: void _KFAST<false, true, true>(unsigned char const*, int, int, int, int, std::vector<Keypoint, std::allocator<Keypoint> >&, unsigned char) (KFastAVX2.h:401)
==21867==    by 0x5A1D5A: KFAST<false, false> (KFastAVX2.h:493)
==21867==  Address 0x630ef43 is 307,187 bytes inside a block of size 307,200 alloc'd

From reading the code what I can understand is that, on each row when processing the final set of columns (i.e. < 32 columns left), you load in chunks of 32 bytes and mask out the data beyond the end of the row. This means that for the final row you will load data beyond the end of the buffer, and valgrind thinks this is bad. 

I couldn't really find any info on the safety of doing this with AVX, so I wondering if you could comment on it, or maybe point me to some documentation?

**Comment by komrad36** [comment]
Hi, thanks for checking out KFAST and running Valgrind on it, that's cool!

You're indeed correct that I read off the end of the buffer if it's not a multiple of 32 bytes, and that it doesn't affect the output because we mask off the remainder.

It is NOT safe in the general sense; the CPU doesn't know or care that I read past the _buffer_ specifically, but if the buffer were, for example, immediately followed by memory that is not mapped, or that the program does not have permission to read, the program would crash.

In a production environment you'd want to guarantee the safety of that access by over-allocating the buffer passed to KFAST by (at least) 32 bytes. That way you can be sure that no matter what the conditions of the memory surrounding the buffer, the access is safe.

It would not be a bad idea for me to document this somewhere in KFAST; I vaguely remember doing so for some of my stuff but I don't see such a warning in KFAST anywhere.

It's possible to solve this inside KFAST of course, by not reading past the end of the buffer - either by a special load sequence for < 32 bytes or by using AVX maskloads. But both options are slower and unnecessary; overallocating by a bit to allow simplified vector loads/stores is faster and safe, and for just 32 bytes of extra memory. I just should have documented it better :)

Thanks again for looking into this and asking about it!

**Comment by nedm2** [comment]
Thanks for the response, I was also thinking overallocation would be the correct solution but wanted to make sure I wasn't misunderstanding something, thanks for your insights on this.
